#page title
page_title                                : LinkBin                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1584335419                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : LinkBin                                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free to download                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Easily save links on iPhone, iPad and Mac

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : David Haydl                            
your_link                                 : https://twitter.com/DavidHaydl                     
your_city                                 : Graz                                
email_address                             : david.haydl@gmail.com
facebook_username                         :                                          
instagram_username                        : david_h93
twitter_username                          : DavidHaydl
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Save links and reference them later
    description                           : Save links manually, via the iOS and iPadOS share extension or the Safari browser extension on Mac.
    fontawesome_icon_name                 : link-horizontal
    
  - title                                 : Organize everything with labels
    description                           : To keep everything neat and tidy, LinkBin allows you to organize your links with labels.
    fontawesome_icon_name                 : tag

  - title                                 : iCloud sync
    description                           : Sync all links across all of your devices, thanks to iCloud.
    fontawesome_icon_name                 : cloud

  - title                                 : Multiple app icons
    description                           : Customize the app with an app icon of your desired style.
    fontawesome_icon_name                 : compass-drafting



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
