page_title                                : LinkBin
ios_app_id                                : 1584335419
ios_app_country                           : us
appstore_link                             :            # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :
presskit_download_link                    : https://drive.google.com/drive/folders/1eCs2RIvz7yYNgP9zBTy7T9Q7uLOGRLsd?usp=sharing
app_icon                                  : assets/appicon.png
app_name                                  : LinkBin
app_price                                 : Free to download
app_description                           : Easily save links on iPhone, iPad and Mac
enable_smart_app_banner                   : true


your_name                                 : David Haydl                            
your_link                                 : https://twitter.com/DavidHaydl                     
your_city                                 : Graz🇦🇹                              
email_address                             : david.haydl@gmail.com
facebook_username                         :                                          
instagram_username                        : david_h93
twitter_username                          : LinkBin_App
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title                                 : Save links and reference them later
    description                           : Save links manually, via the iOS and iPadOS share extension or the Safari browser extension on Mac.
    fontawesome_icon_name                 : link
  - title                                 : Organize everything with labels
    description                           : To keep everything neat and tidy, LinkBin allows you to organize your links with labels.
    fontawesome_icon_name                 : tag
  - title                                 : iCloud sync
    description                           : Sync all links across all of your devices, thanks to iCloud.
    fontawesome_icon_name                 : cloud
  - title                                 : Send links to other apps easily
    description                           : Want to process a link in an other app further? No problem, just use the integrated share sheet on iOS or the share menu on macOS.
    fontawesome_icon_name                 : share-square
  - title                                 : Supports Shortcuts
    description                           : Automate your link workflow with the help of the Shortcuts app on iOS, iPadOS and macOS Monterey or newer.
    fontawesome_icon_name                 : robot
  - title                                 : Multiple app icons
    description                           : Customize the app with an app icon of your desired style.
    fontawesome_icon_name                 : drafting-compass
  - title                                 : Widgets
    description                           : Interact with your links through widgets on your homescreen or in the notification center on macOS
    fontawesome_icon_name                 : square
  - title                                 : Copy links as HTML, Markdown or Rich-Text
    description                           : Save one or several links as HTML, Markdown or Rich-Text with just a few clicks. This is for example perfect for inserting links into a WordPress article.
    fontawesome_icon_name                 : clipboard



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               :                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
